image: alpine:3.18

make:
  stage: build
  tags:
    - comp2300
  before_script:
    - apk add alpine-sdk linux-lts-dev linux-headers
  script:
    - cd vvsfs
    - make -C /usr/src/linux-headers-6.1.55-0-lts
  artifacts:
    paths:
      - vvsfs/mkfs.vvsfs
      - vvsfs/vvsfs.ko
