build:
  stage: build
  tags:
    - comp2300
  parallel:
    matrix:
      - IMAGE:
        - alpine:3.17
        - alpine:3.18
  image: $IMAGE
  before_script:
    - apk add binutils gcc libc-dev make linux-lts-dev
  script:
    - cd vvsfs
    - make KDIR=/lib/modules/*/build
  artifacts:
    paths:
      - vvsfs/mkfs.vvsfs
      - vvsfs/vvsfs.ko
