image: alpine:3.18

make:
  stage: build
  tags:
    - comp2300
  before_script:
    - apk add binutils gcc libc-dev make alpine-sdk linux-lts-dev linux-headers
  script:
    - cd vvsfs
    - make KDIR=/lib/modules/6.1.55-0-lts/build
  artifacts:
    paths:
      - vvsfs/mkfs.vvsfs
      - vvsfs/vvsfs.ko
